language: rust
rust:
  - 1.41.0
  - stable
  - beta
  - nightly
sudo: required
dist: bionic
#cache: cargo
# Needed for codecov reporting
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libssl-dev
env: RUST_BACKTRACE=full
before_script:
  - cargo install --force cargo-when
  - |
    if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      rustup component add rustfmt
      cargo install --force cargo-audit
    fi
script:
  - cargo test --tests --examples
  - cargo test --doc
  - cargo test --all-features
  - cargo build --features futures-01 --no-default-features
  - cargo build --features futures-03 --no-default-features
  - cargo when --equals TRAVIS_RUST_VERSION=stable fmt --all -- --check
  - cargo when --equals TRAVIS_RUST_VERSION=stable audit
after_success: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin &&
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
notifications:
  email:
    on_success: never
